// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: agent_mod_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentModConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ModConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModConfigRequest) Reset() {
	*x = AgentModConfigRequest{}
	mi := &file_agent_mod_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModConfigRequest) ProtoMessage() {}

func (x *AgentModConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_mod_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModConfigRequest.ProtoReflect.Descriptor instead.
func (*AgentModConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_mod_service_proto_rawDescGZIP(), []int{0}
}

func (x *AgentModConfigRequest) GetConfig() *ModConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type AgentModConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ModConfig           `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentModConfigResponse) Reset() {
	*x = AgentModConfigResponse{}
	mi := &file_agent_mod_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentModConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentModConfigResponse) ProtoMessage() {}

func (x *AgentModConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_mod_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentModConfigResponse.ProtoReflect.Descriptor instead.
func (*AgentModConfigResponse) Descriptor() ([]byte, []int) {
	return file_agent_mod_service_proto_rawDescGZIP(), []int{1}
}

func (x *AgentModConfigResponse) GetConfigs() []*ModConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ModConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModConfig) Reset() {
	*x = ModConfig{}
	mi := &file_agent_mod_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModConfig) ProtoMessage() {}

func (x *ModConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_mod_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModConfig.ProtoReflect.Descriptor instead.
func (*ModConfig) Descriptor() ([]byte, []int) {
	return file_agent_mod_service_proto_rawDescGZIP(), []int{2}
}

func (x *ModConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModConfig) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_agent_mod_service_proto protoreflect.FileDescriptor

const file_agent_mod_service_proto_rawDesc = "" +
	"\n" +
	"\x17agent_mod_service.proto\";\n" +
	"\x15AgentModConfigRequest\x12\"\n" +
	"\x06config\x18\x01 \x01(\v2\n" +
	".ModConfigR\x06config\">\n" +
	"\x16AgentModConfigResponse\x12$\n" +
	"\aconfigs\x18\x01 \x03(\v2\n" +
	".ModConfigR\aconfigs\"O\n" +
	"\tModConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent2^\n" +
	"\x15AgentModConfigService\x12E\n" +
	"\x0eSyncModConfigs\x12\x16.AgentModConfigRequest\x1a\x17.AgentModConfigResponse(\x010\x01B?Z=github.com/SatisfactoryServerManager/ssmcloud-resources/protob\x06proto3"

var (
	file_agent_mod_service_proto_rawDescOnce sync.Once
	file_agent_mod_service_proto_rawDescData []byte
)

func file_agent_mod_service_proto_rawDescGZIP() []byte {
	file_agent_mod_service_proto_rawDescOnce.Do(func() {
		file_agent_mod_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_mod_service_proto_rawDesc), len(file_agent_mod_service_proto_rawDesc)))
	})
	return file_agent_mod_service_proto_rawDescData
}

var file_agent_mod_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agent_mod_service_proto_goTypes = []any{
	(*AgentModConfigRequest)(nil),  // 0: AgentModConfigRequest
	(*AgentModConfigResponse)(nil), // 1: AgentModConfigResponse
	(*ModConfig)(nil),              // 2: ModConfig
}
var file_agent_mod_service_proto_depIdxs = []int32{
	2, // 0: AgentModConfigRequest.config:type_name -> ModConfig
	2, // 1: AgentModConfigResponse.configs:type_name -> ModConfig
	0, // 2: AgentModConfigService.SyncModConfigs:input_type -> AgentModConfigRequest
	1, // 3: AgentModConfigService.SyncModConfigs:output_type -> AgentModConfigResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_mod_service_proto_init() }
func file_agent_mod_service_proto_init() {
	if File_agent_mod_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_mod_service_proto_rawDesc), len(file_agent_mod_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_mod_service_proto_goTypes,
		DependencyIndexes: file_agent_mod_service_proto_depIdxs,
		MessageInfos:      file_agent_mod_service_proto_msgTypes,
	}.Build()
	File_agent_mod_service_proto = out.File
	file_agent_mod_service_proto_goTypes = nil
	file_agent_mod_service_proto_depIdxs = nil
}
