// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: agent_task_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Completed     bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	Retries       int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTask) Reset() {
	*x = AgentTask{}
	mi := &file_agent_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTask) ProtoMessage() {}

func (x *AgentTask) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTask.ProtoReflect.Descriptor instead.
func (*AgentTask) Descriptor() ([]byte, []int) {
	return file_agent_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *AgentTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentTask) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentTask) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AgentTask) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *AgentTask) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type AgentTaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*AgentTask           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTaskList) Reset() {
	*x = AgentTaskList{}
	mi := &file_agent_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskList) ProtoMessage() {}

func (x *AgentTaskList) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskList.ProtoReflect.Descriptor instead.
func (*AgentTaskList) Descriptor() ([]byte, []int) {
	return file_agent_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *AgentTaskList) GetTasks() []*AgentTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type AgentTaskCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTaskCompletedRequest) Reset() {
	*x = AgentTaskCompletedRequest{}
	mi := &file_agent_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskCompletedRequest) ProtoMessage() {}

func (x *AgentTaskCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskCompletedRequest.ProtoReflect.Descriptor instead.
func (*AgentTaskCompletedRequest) Descriptor() ([]byte, []int) {
	return file_agent_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *AgentTaskCompletedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AgentTaskFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTaskFailedRequest) Reset() {
	*x = AgentTaskFailedRequest{}
	mi := &file_agent_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskFailedRequest) ProtoMessage() {}

func (x *AgentTaskFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskFailedRequest.ProtoReflect.Descriptor instead.
func (*AgentTaskFailedRequest) Descriptor() ([]byte, []int) {
	return file_agent_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *AgentTaskFailedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_agent_task_service_proto protoreflect.FileDescriptor

const file_agent_task_service_proto_rawDesc = "" +
	"\n" +
	"\x18agent_task_service.proto\x1a\vempty.proto\"\x7f\n" +
	"\tAgentTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\"1\n" +
	"\rAgentTaskList\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".AgentTaskR\x05tasks\"+\n" +
	"\x19AgentTaskCompletedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16AgentTaskFailedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xb1\x01\n" +
	"\x10AgentTaskService\x12'\n" +
	"\rGetAgentTasks\x12\x06.Empty\x1a\x0e.AgentTaskList\x12<\n" +
	"\x16MarkAgentTaskCompleted\x12\x1a.AgentTaskCompletedRequest\x1a\x06.Empty\x126\n" +
	"\x13MarkAgentTaskFailed\x12\x17.AgentTaskFailedRequest\x1a\x06.EmptyB?Z=github.com/SatisfactoryServerManager/ssmcloud-resources/protob\x06proto3"

var (
	file_agent_task_service_proto_rawDescOnce sync.Once
	file_agent_task_service_proto_rawDescData []byte
)

func file_agent_task_service_proto_rawDescGZIP() []byte {
	file_agent_task_service_proto_rawDescOnce.Do(func() {
		file_agent_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_task_service_proto_rawDesc), len(file_agent_task_service_proto_rawDesc)))
	})
	return file_agent_task_service_proto_rawDescData
}

var file_agent_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_task_service_proto_goTypes = []any{
	(*AgentTask)(nil),                 // 0: AgentTask
	(*AgentTaskList)(nil),             // 1: AgentTaskList
	(*AgentTaskCompletedRequest)(nil), // 2: AgentTaskCompletedRequest
	(*AgentTaskFailedRequest)(nil),    // 3: AgentTaskFailedRequest
	(*Empty)(nil),                     // 4: Empty
}
var file_agent_task_service_proto_depIdxs = []int32{
	0, // 0: AgentTaskList.tasks:type_name -> AgentTask
	4, // 1: AgentTaskService.GetAgentTasks:input_type -> Empty
	2, // 2: AgentTaskService.MarkAgentTaskCompleted:input_type -> AgentTaskCompletedRequest
	3, // 3: AgentTaskService.MarkAgentTaskFailed:input_type -> AgentTaskFailedRequest
	1, // 4: AgentTaskService.GetAgentTasks:output_type -> AgentTaskList
	4, // 5: AgentTaskService.MarkAgentTaskCompleted:output_type -> Empty
	4, // 6: AgentTaskService.MarkAgentTaskFailed:output_type -> Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_task_service_proto_init() }
func file_agent_task_service_proto_init() {
	if File_agent_task_service_proto != nil {
		return
	}
	file_empty_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_task_service_proto_rawDesc), len(file_agent_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_task_service_proto_goTypes,
		DependencyIndexes: file_agent_task_service_proto_depIdxs,
		MessageInfos:      file_agent_task_service_proto_msgTypes,
	}.Build()
	File_agent_task_service_proto = out.File
	file_agent_task_service_proto_goTypes = nil
	file_agent_task_service_proto_depIdxs = nil
}
