// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: agent_config_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentConfigService_GetAgentConfig_FullMethodName             = "/AgentConfigService/GetAgentConfig"
	AgentConfigService_UpdateAgentConfigVersionIp_FullMethodName = "/AgentConfigService/UpdateAgentConfigVersionIp"
)

// AgentConfigServiceClient is the client API for AgentConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentConfigServiceClient interface {
	GetAgentConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentConfigResponse, error)
	UpdateAgentConfigVersionIp(ctx context.Context, in *UpdateAgentConfigRequest, opts ...grpc.CallOption) (*Empty, error)
}

type agentConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentConfigServiceClient(cc grpc.ClientConnInterface) AgentConfigServiceClient {
	return &agentConfigServiceClient{cc}
}

func (c *agentConfigServiceClient) GetAgentConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigResponse)
	err := c.cc.Invoke(ctx, AgentConfigService_GetAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentConfigServiceClient) UpdateAgentConfigVersionIp(ctx context.Context, in *UpdateAgentConfigRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentConfigService_UpdateAgentConfigVersionIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentConfigServiceServer is the server API for AgentConfigService service.
// All implementations must embed UnimplementedAgentConfigServiceServer
// for forward compatibility.
type AgentConfigServiceServer interface {
	GetAgentConfig(context.Context, *Empty) (*AgentConfigResponse, error)
	UpdateAgentConfigVersionIp(context.Context, *UpdateAgentConfigRequest) (*Empty, error)
	mustEmbedUnimplementedAgentConfigServiceServer()
}

// UnimplementedAgentConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentConfigServiceServer struct{}

func (UnimplementedAgentConfigServiceServer) GetAgentConfig(context.Context, *Empty) (*AgentConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentConfig not implemented")
}
func (UnimplementedAgentConfigServiceServer) UpdateAgentConfigVersionIp(context.Context, *UpdateAgentConfigRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentConfigVersionIp not implemented")
}
func (UnimplementedAgentConfigServiceServer) mustEmbedUnimplementedAgentConfigServiceServer() {}
func (UnimplementedAgentConfigServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentConfigServiceServer will
// result in compilation errors.
type UnsafeAgentConfigServiceServer interface {
	mustEmbedUnimplementedAgentConfigServiceServer()
}

func RegisterAgentConfigServiceServer(s grpc.ServiceRegistrar, srv AgentConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentConfigService_ServiceDesc, srv)
}

func _AgentConfigService_GetAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServiceServer).GetAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfigService_GetAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServiceServer).GetAgentConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentConfigService_UpdateAgentConfigVersionIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServiceServer).UpdateAgentConfigVersionIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfigService_UpdateAgentConfigVersionIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServiceServer).UpdateAgentConfigVersionIp(ctx, req.(*UpdateAgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentConfigService_ServiceDesc is the grpc.ServiceDesc for AgentConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AgentConfigService",
	HandlerType: (*AgentConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentConfig",
			Handler:    _AgentConfigService_GetAgentConfig_Handler,
		},
		{
			MethodName: "UpdateAgentConfigVersionIp",
			Handler:    _AgentConfigService_UpdateAgentConfigVersionIp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_config_service.proto",
}
