// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: agent_mod_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentModConfigService_SyncModConfigs_FullMethodName = "/AgentModConfigService/SyncModConfigs"
)

// AgentModConfigServiceClient is the client API for AgentModConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentModConfigServiceClient interface {
	SyncModConfigs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentModConfigRequest, AgentModConfigResponse], error)
}

type agentModConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentModConfigServiceClient(cc grpc.ClientConnInterface) AgentModConfigServiceClient {
	return &agentModConfigServiceClient{cc}
}

func (c *agentModConfigServiceClient) SyncModConfigs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentModConfigRequest, AgentModConfigResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentModConfigService_ServiceDesc.Streams[0], AgentModConfigService_SyncModConfigs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentModConfigRequest, AgentModConfigResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentModConfigService_SyncModConfigsClient = grpc.BidiStreamingClient[AgentModConfigRequest, AgentModConfigResponse]

// AgentModConfigServiceServer is the server API for AgentModConfigService service.
// All implementations must embed UnimplementedAgentModConfigServiceServer
// for forward compatibility.
type AgentModConfigServiceServer interface {
	SyncModConfigs(grpc.BidiStreamingServer[AgentModConfigRequest, AgentModConfigResponse]) error
	mustEmbedUnimplementedAgentModConfigServiceServer()
}

// UnimplementedAgentModConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentModConfigServiceServer struct{}

func (UnimplementedAgentModConfigServiceServer) SyncModConfigs(grpc.BidiStreamingServer[AgentModConfigRequest, AgentModConfigResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SyncModConfigs not implemented")
}
func (UnimplementedAgentModConfigServiceServer) mustEmbedUnimplementedAgentModConfigServiceServer() {}
func (UnimplementedAgentModConfigServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentModConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentModConfigServiceServer will
// result in compilation errors.
type UnsafeAgentModConfigServiceServer interface {
	mustEmbedUnimplementedAgentModConfigServiceServer()
}

func RegisterAgentModConfigServiceServer(s grpc.ServiceRegistrar, srv AgentModConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentModConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentModConfigService_ServiceDesc, srv)
}

func _AgentModConfigService_SyncModConfigs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentModConfigServiceServer).SyncModConfigs(&grpc.GenericServerStream[AgentModConfigRequest, AgentModConfigResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentModConfigService_SyncModConfigsServer = grpc.BidiStreamingServer[AgentModConfigRequest, AgentModConfigResponse]

// AgentModConfigService_ServiceDesc is the grpc.ServiceDesc for AgentModConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentModConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AgentModConfigService",
	HandlerType: (*AgentModConfigServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncModConfigs",
			Handler:       _AgentModConfigService_SyncModConfigs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent_mod_service.proto",
}
