// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: agent_mod_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentModConfigService_GetModConfig_FullMethodName    = "/AgentModConfigService/GetModConfig"
	AgentModConfigService_UpdateModConfig_FullMethodName = "/AgentModConfigService/UpdateModConfig"
)

// AgentModConfigServiceClient is the client API for AgentModConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentModConfigServiceClient interface {
	GetModConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentModConfigResponse, error)
	UpdateModConfig(ctx context.Context, in *AgentModConfigRequest, opts ...grpc.CallOption) (*Empty, error)
}

type agentModConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentModConfigServiceClient(cc grpc.ClientConnInterface) AgentModConfigServiceClient {
	return &agentModConfigServiceClient{cc}
}

func (c *agentModConfigServiceClient) GetModConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentModConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentModConfigResponse)
	err := c.cc.Invoke(ctx, AgentModConfigService_GetModConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentModConfigServiceClient) UpdateModConfig(ctx context.Context, in *AgentModConfigRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentModConfigService_UpdateModConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentModConfigServiceServer is the server API for AgentModConfigService service.
// All implementations must embed UnimplementedAgentModConfigServiceServer
// for forward compatibility.
type AgentModConfigServiceServer interface {
	GetModConfig(context.Context, *Empty) (*AgentModConfigResponse, error)
	UpdateModConfig(context.Context, *AgentModConfigRequest) (*Empty, error)
	mustEmbedUnimplementedAgentModConfigServiceServer()
}

// UnimplementedAgentModConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentModConfigServiceServer struct{}

func (UnimplementedAgentModConfigServiceServer) GetModConfig(context.Context, *Empty) (*AgentModConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModConfig not implemented")
}
func (UnimplementedAgentModConfigServiceServer) UpdateModConfig(context.Context, *AgentModConfigRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModConfig not implemented")
}
func (UnimplementedAgentModConfigServiceServer) mustEmbedUnimplementedAgentModConfigServiceServer() {}
func (UnimplementedAgentModConfigServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentModConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentModConfigServiceServer will
// result in compilation errors.
type UnsafeAgentModConfigServiceServer interface {
	mustEmbedUnimplementedAgentModConfigServiceServer()
}

func RegisterAgentModConfigServiceServer(s grpc.ServiceRegistrar, srv AgentModConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentModConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentModConfigService_ServiceDesc, srv)
}

func _AgentModConfigService_GetModConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentModConfigServiceServer).GetModConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentModConfigService_GetModConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentModConfigServiceServer).GetModConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentModConfigService_UpdateModConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentModConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentModConfigServiceServer).UpdateModConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentModConfigService_UpdateModConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentModConfigServiceServer).UpdateModConfig(ctx, req.(*AgentModConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentModConfigService_ServiceDesc is the grpc.ServiceDesc for AgentModConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentModConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AgentModConfigService",
	HandlerType: (*AgentModConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModConfig",
			Handler:    _AgentModConfigService_GetModConfig_Handler,
		},
		{
			MethodName: "UpdateModConfig",
			Handler:    _AgentModConfigService_UpdateModConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_mod_service.proto",
}
