// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent_log_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLogService_StreamLog_FullMethodName = "/AgentLogService/StreamLog"
)

// AgentLogServiceClient is the client API for AgentLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentLogServiceClient interface {
	StreamLog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AgentLogLineRequest, Empty], error)
}

type agentLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLogServiceClient(cc grpc.ClientConnInterface) AgentLogServiceClient {
	return &agentLogServiceClient{cc}
}

func (c *agentLogServiceClient) StreamLog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AgentLogLineRequest, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLogService_ServiceDesc.Streams[0], AgentLogService_StreamLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentLogLineRequest, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLogService_StreamLogClient = grpc.ClientStreamingClient[AgentLogLineRequest, Empty]

// AgentLogServiceServer is the server API for AgentLogService service.
// All implementations must embed UnimplementedAgentLogServiceServer
// for forward compatibility.
type AgentLogServiceServer interface {
	StreamLog(grpc.ClientStreamingServer[AgentLogLineRequest, Empty]) error
	mustEmbedUnimplementedAgentLogServiceServer()
}

// UnimplementedAgentLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLogServiceServer struct{}

func (UnimplementedAgentLogServiceServer) StreamLog(grpc.ClientStreamingServer[AgentLogLineRequest, Empty]) error {
	return status.Error(codes.Unimplemented, "method StreamLog not implemented")
}
func (UnimplementedAgentLogServiceServer) mustEmbedUnimplementedAgentLogServiceServer() {}
func (UnimplementedAgentLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeAgentLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLogServiceServer will
// result in compilation errors.
type UnsafeAgentLogServiceServer interface {
	mustEmbedUnimplementedAgentLogServiceServer()
}

func RegisterAgentLogServiceServer(s grpc.ServiceRegistrar, srv AgentLogServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLogService_ServiceDesc, srv)
}

func _AgentLogService_StreamLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLogServiceServer).StreamLog(&grpc.GenericServerStream[AgentLogLineRequest, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLogService_StreamLogServer = grpc.ClientStreamingServer[AgentLogLineRequest, Empty]

// AgentLogService_ServiceDesc is the grpc.ServiceDesc for AgentLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AgentLogService",
	HandlerType: (*AgentLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLog",
			Handler:       _AgentLogService_StreamLog_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent_log_service.proto",
}
