// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent_state_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentStateService_UpdateAgentStateStream_FullMethodName = "/AgentStateService/UpdateAgentStateStream"
	AgentStateService_UpdateAgentState_FullMethodName       = "/AgentStateService/UpdateAgentState"
)

// AgentStateServiceClient is the client API for AgentStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentStateServiceClient interface {
	UpdateAgentStateStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AgentStateRequest, Empty], error)
	UpdateAgentState(ctx context.Context, in *AgentStateRequest, opts ...grpc.CallOption) (*Empty, error)
}

type agentStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentStateServiceClient(cc grpc.ClientConnInterface) AgentStateServiceClient {
	return &agentStateServiceClient{cc}
}

func (c *agentStateServiceClient) UpdateAgentStateStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AgentStateRequest, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentStateService_ServiceDesc.Streams[0], AgentStateService_UpdateAgentStateStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentStateRequest, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStateService_UpdateAgentStateStreamClient = grpc.ClientStreamingClient[AgentStateRequest, Empty]

func (c *agentStateServiceClient) UpdateAgentState(ctx context.Context, in *AgentStateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentStateService_UpdateAgentState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentStateServiceServer is the server API for AgentStateService service.
// All implementations must embed UnimplementedAgentStateServiceServer
// for forward compatibility.
type AgentStateServiceServer interface {
	UpdateAgentStateStream(grpc.ClientStreamingServer[AgentStateRequest, Empty]) error
	UpdateAgentState(context.Context, *AgentStateRequest) (*Empty, error)
	mustEmbedUnimplementedAgentStateServiceServer()
}

// UnimplementedAgentStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentStateServiceServer struct{}

func (UnimplementedAgentStateServiceServer) UpdateAgentStateStream(grpc.ClientStreamingServer[AgentStateRequest, Empty]) error {
	return status.Error(codes.Unimplemented, "method UpdateAgentStateStream not implemented")
}
func (UnimplementedAgentStateServiceServer) UpdateAgentState(context.Context, *AgentStateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentState not implemented")
}
func (UnimplementedAgentStateServiceServer) mustEmbedUnimplementedAgentStateServiceServer() {}
func (UnimplementedAgentStateServiceServer) testEmbeddedByValue()                           {}

// UnsafeAgentStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentStateServiceServer will
// result in compilation errors.
type UnsafeAgentStateServiceServer interface {
	mustEmbedUnimplementedAgentStateServiceServer()
}

func RegisterAgentStateServiceServer(s grpc.ServiceRegistrar, srv AgentStateServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentStateService_ServiceDesc, srv)
}

func _AgentStateService_UpdateAgentStateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentStateServiceServer).UpdateAgentStateStream(&grpc.GenericServerStream[AgentStateRequest, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStateService_UpdateAgentStateStreamServer = grpc.ClientStreamingServer[AgentStateRequest, Empty]

func _AgentStateService_UpdateAgentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentStateServiceServer).UpdateAgentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentStateService_UpdateAgentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentStateServiceServer).UpdateAgentState(ctx, req.(*AgentStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentStateService_ServiceDesc is the grpc.ServiceDesc for AgentStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AgentStateService",
	HandlerType: (*AgentStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAgentState",
			Handler:    _AgentStateService_UpdateAgentState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateAgentStateStream",
			Handler:       _AgentStateService_UpdateAgentStateStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent_state_service.proto",
}
