// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent_task_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentTaskService_GetAgentTasks_FullMethodName          = "/AgentTaskService/GetAgentTasks"
	AgentTaskService_MarkAgentTaskCompleted_FullMethodName = "/AgentTaskService/MarkAgentTaskCompleted"
	AgentTaskService_MarkAgentTaskFailed_FullMethodName    = "/AgentTaskService/MarkAgentTaskFailed"
)

// AgentTaskServiceClient is the client API for AgentTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentTaskServiceClient interface {
	GetAgentTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentTaskList, error)
	MarkAgentTaskCompleted(ctx context.Context, in *AgentTaskCompletedRequest, opts ...grpc.CallOption) (*Empty, error)
	MarkAgentTaskFailed(ctx context.Context, in *AgentTaskFailedRequest, opts ...grpc.CallOption) (*Empty, error)
}

type agentTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentTaskServiceClient(cc grpc.ClientConnInterface) AgentTaskServiceClient {
	return &agentTaskServiceClient{cc}
}

func (c *agentTaskServiceClient) GetAgentTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AgentTaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentTaskList)
	err := c.cc.Invoke(ctx, AgentTaskService_GetAgentTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentTaskServiceClient) MarkAgentTaskCompleted(ctx context.Context, in *AgentTaskCompletedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentTaskService_MarkAgentTaskCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentTaskServiceClient) MarkAgentTaskFailed(ctx context.Context, in *AgentTaskFailedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentTaskService_MarkAgentTaskFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentTaskServiceServer is the server API for AgentTaskService service.
// All implementations must embed UnimplementedAgentTaskServiceServer
// for forward compatibility.
type AgentTaskServiceServer interface {
	GetAgentTasks(context.Context, *Empty) (*AgentTaskList, error)
	MarkAgentTaskCompleted(context.Context, *AgentTaskCompletedRequest) (*Empty, error)
	MarkAgentTaskFailed(context.Context, *AgentTaskFailedRequest) (*Empty, error)
	mustEmbedUnimplementedAgentTaskServiceServer()
}

// UnimplementedAgentTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentTaskServiceServer struct{}

func (UnimplementedAgentTaskServiceServer) GetAgentTasks(context.Context, *Empty) (*AgentTaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentTasks not implemented")
}
func (UnimplementedAgentTaskServiceServer) MarkAgentTaskCompleted(context.Context, *AgentTaskCompletedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAgentTaskCompleted not implemented")
}
func (UnimplementedAgentTaskServiceServer) MarkAgentTaskFailed(context.Context, *AgentTaskFailedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAgentTaskFailed not implemented")
}
func (UnimplementedAgentTaskServiceServer) mustEmbedUnimplementedAgentTaskServiceServer() {}
func (UnimplementedAgentTaskServiceServer) testEmbeddedByValue()                          {}

// UnsafeAgentTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentTaskServiceServer will
// result in compilation errors.
type UnsafeAgentTaskServiceServer interface {
	mustEmbedUnimplementedAgentTaskServiceServer()
}

func RegisterAgentTaskServiceServer(s grpc.ServiceRegistrar, srv AgentTaskServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentTaskService_ServiceDesc, srv)
}

func _AgentTaskService_GetAgentTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTaskServiceServer).GetAgentTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentTaskService_GetAgentTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTaskServiceServer).GetAgentTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentTaskService_MarkAgentTaskCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentTaskCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTaskServiceServer).MarkAgentTaskCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentTaskService_MarkAgentTaskCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTaskServiceServer).MarkAgentTaskCompleted(ctx, req.(*AgentTaskCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentTaskService_MarkAgentTaskFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentTaskFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTaskServiceServer).MarkAgentTaskFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentTaskService_MarkAgentTaskFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTaskServiceServer).MarkAgentTaskFailed(ctx, req.(*AgentTaskFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentTaskService_ServiceDesc is the grpc.ServiceDesc for AgentTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AgentTaskService",
	HandlerType: (*AgentTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentTasks",
			Handler:    _AgentTaskService_GetAgentTasks_Handler,
		},
		{
			MethodName: "MarkAgentTaskCompleted",
			Handler:    _AgentTaskService_MarkAgentTaskCompleted_Handler,
		},
		{
			MethodName: "MarkAgentTaskFailed",
			Handler:    _AgentTaskService_MarkAgentTaskFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_task_service.proto",
}
