// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: frontend_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckUserExistsOrCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Eid           string                 `protobuf:"bytes,2,opt,name=eid,proto3" json:"eid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistsOrCreateRequest) Reset() {
	*x = CheckUserExistsOrCreateRequest{}
	mi := &file_frontend_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistsOrCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistsOrCreateRequest) ProtoMessage() {}

func (x *CheckUserExistsOrCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistsOrCreateRequest.ProtoReflect.Descriptor instead.
func (*CheckUserExistsOrCreateRequest) Descriptor() ([]byte, []int) {
	return file_frontend_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUserExistsOrCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckUserExistsOrCreateRequest) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

var File_frontend_service_proto protoreflect.FileDescriptor

const file_frontend_service_proto_rawDesc = "" +
	"\n" +
	"\x16frontend_service.proto\x1a\vempty.proto\"H\n" +
	"\x1eCheckUserExistsOrCreateRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03eid\x18\x02 \x01(\tR\x03eid2U\n" +
	"\x0fFrontendService\x12B\n" +
	"\x17CheckUserExistsOrCreate\x12\x1f.CheckUserExistsOrCreateRequest\x1a\x06.EmptyB?Z=github.com/SatisfactoryServerManager/ssmcloud-resources/protob\x06proto3"

var (
	file_frontend_service_proto_rawDescOnce sync.Once
	file_frontend_service_proto_rawDescData []byte
)

func file_frontend_service_proto_rawDescGZIP() []byte {
	file_frontend_service_proto_rawDescOnce.Do(func() {
		file_frontend_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontend_service_proto_rawDesc), len(file_frontend_service_proto_rawDesc)))
	})
	return file_frontend_service_proto_rawDescData
}

var file_frontend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frontend_service_proto_goTypes = []any{
	(*CheckUserExistsOrCreateRequest)(nil), // 0: CheckUserExistsOrCreateRequest
	(*Empty)(nil),                          // 1: Empty
}
var file_frontend_service_proto_depIdxs = []int32{
	0, // 0: FrontendService.CheckUserExistsOrCreate:input_type -> CheckUserExistsOrCreateRequest
	1, // 1: FrontendService.CheckUserExistsOrCreate:output_type -> Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frontend_service_proto_init() }
func file_frontend_service_proto_init() {
	if File_frontend_service_proto != nil {
		return
	}
	file_empty_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_service_proto_rawDesc), len(file_frontend_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_service_proto_goTypes,
		DependencyIndexes: file_frontend_service_proto_depIdxs,
		MessageInfos:      file_frontend_service_proto_msgTypes,
	}.Build()
	File_frontend_service_proto = out.File
	file_frontend_service_proto_goTypes = nil
	file_frontend_service_proto_depIdxs = nil
}
