// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: frontend_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FrontendService_CheckUserExistsOrCreate_FullMethodName = "/FrontendService/CheckUserExistsOrCreate"
	FrontendService_GetMyUser_FullMethodName               = "/FrontendService/GetMyUser"
	FrontendService_GetMyUserLinkedAccounts_FullMethodName = "/FrontendService/GetMyUserLinkedAccounts"
	FrontendService_GetMyUserActiveAccount_FullMethodName  = "/FrontendService/GetMyUserActiveAccount"
)

// FrontendServiceClient is the client API for FrontendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontendServiceClient interface {
	CheckUserExistsOrCreate(ctx context.Context, in *CheckUserExistsOrCreateRequest, opts ...grpc.CallOption) (*Empty, error)
	GetMyUser(ctx context.Context, in *GetMyUserRequest, opts ...grpc.CallOption) (*GetMyUserResponse, error)
	GetMyUserLinkedAccounts(ctx context.Context, in *GetMyUserLinkedAccountsRequest, opts ...grpc.CallOption) (*GetMyUserLinkedAccountsResponse, error)
	GetMyUserActiveAccount(ctx context.Context, in *GetMyUserActiveAccountsRequest, opts ...grpc.CallOption) (*GetMyUserActiveAccountsResponse, error)
}

type frontendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontendServiceClient(cc grpc.ClientConnInterface) FrontendServiceClient {
	return &frontendServiceClient{cc}
}

func (c *frontendServiceClient) CheckUserExistsOrCreate(ctx context.Context, in *CheckUserExistsOrCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FrontendService_CheckUserExistsOrCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) GetMyUser(ctx context.Context, in *GetMyUserRequest, opts ...grpc.CallOption) (*GetMyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyUserResponse)
	err := c.cc.Invoke(ctx, FrontendService_GetMyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) GetMyUserLinkedAccounts(ctx context.Context, in *GetMyUserLinkedAccountsRequest, opts ...grpc.CallOption) (*GetMyUserLinkedAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyUserLinkedAccountsResponse)
	err := c.cc.Invoke(ctx, FrontendService_GetMyUserLinkedAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) GetMyUserActiveAccount(ctx context.Context, in *GetMyUserActiveAccountsRequest, opts ...grpc.CallOption) (*GetMyUserActiveAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyUserActiveAccountsResponse)
	err := c.cc.Invoke(ctx, FrontendService_GetMyUserActiveAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontendServiceServer is the server API for FrontendService service.
// All implementations must embed UnimplementedFrontendServiceServer
// for forward compatibility.
type FrontendServiceServer interface {
	CheckUserExistsOrCreate(context.Context, *CheckUserExistsOrCreateRequest) (*Empty, error)
	GetMyUser(context.Context, *GetMyUserRequest) (*GetMyUserResponse, error)
	GetMyUserLinkedAccounts(context.Context, *GetMyUserLinkedAccountsRequest) (*GetMyUserLinkedAccountsResponse, error)
	GetMyUserActiveAccount(context.Context, *GetMyUserActiveAccountsRequest) (*GetMyUserActiveAccountsResponse, error)
	mustEmbedUnimplementedFrontendServiceServer()
}

// UnimplementedFrontendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrontendServiceServer struct{}

func (UnimplementedFrontendServiceServer) CheckUserExistsOrCreate(context.Context, *CheckUserExistsOrCreateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUserExistsOrCreate not implemented")
}
func (UnimplementedFrontendServiceServer) GetMyUser(context.Context, *GetMyUserRequest) (*GetMyUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyUser not implemented")
}
func (UnimplementedFrontendServiceServer) GetMyUserLinkedAccounts(context.Context, *GetMyUserLinkedAccountsRequest) (*GetMyUserLinkedAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyUserLinkedAccounts not implemented")
}
func (UnimplementedFrontendServiceServer) GetMyUserActiveAccount(context.Context, *GetMyUserActiveAccountsRequest) (*GetMyUserActiveAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyUserActiveAccount not implemented")
}
func (UnimplementedFrontendServiceServer) mustEmbedUnimplementedFrontendServiceServer() {}
func (UnimplementedFrontendServiceServer) testEmbeddedByValue()                         {}

// UnsafeFrontendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontendServiceServer will
// result in compilation errors.
type UnsafeFrontendServiceServer interface {
	mustEmbedUnimplementedFrontendServiceServer()
}

func RegisterFrontendServiceServer(s grpc.ServiceRegistrar, srv FrontendServiceServer) {
	// If the following call panics, it indicates UnimplementedFrontendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FrontendService_ServiceDesc, srv)
}

func _FrontendService_CheckUserExistsOrCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserExistsOrCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).CheckUserExistsOrCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_CheckUserExistsOrCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).CheckUserExistsOrCreate(ctx, req.(*CheckUserExistsOrCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_GetMyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).GetMyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_GetMyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).GetMyUser(ctx, req.(*GetMyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_GetMyUserLinkedAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyUserLinkedAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).GetMyUserLinkedAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_GetMyUserLinkedAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).GetMyUserLinkedAccounts(ctx, req.(*GetMyUserLinkedAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_GetMyUserActiveAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyUserActiveAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).GetMyUserActiveAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_GetMyUserActiveAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).GetMyUserActiveAccount(ctx, req.(*GetMyUserActiveAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FrontendService_ServiceDesc is the grpc.ServiceDesc for FrontendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrontendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FrontendService",
	HandlerType: (*FrontendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUserExistsOrCreate",
			Handler:    _FrontendService_CheckUserExistsOrCreate_Handler,
		},
		{
			MethodName: "GetMyUser",
			Handler:    _FrontendService_GetMyUser_Handler,
		},
		{
			MethodName: "GetMyUserLinkedAccounts",
			Handler:    _FrontendService_GetMyUserLinkedAccounts_Handler,
		},
		{
			MethodName: "GetMyUserActiveAccount",
			Handler:    _FrontendService_GetMyUserActiveAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontend_service.proto",
}
