// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/ssmcloud.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BackupInterval   int32                  `protobuf:"varint,1,opt,name=backupInterval,proto3" json:"backupInterval,omitempty"`
	BackupKeepAmount int32                  `protobuf:"varint,2,opt,name=backupKeepAmount,proto3" json:"backupKeepAmount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_proto_ssmcloud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConfig) GetBackupInterval() int32 {
	if x != nil {
		return x.BackupInterval
	}
	return 0
}

func (x *AgentConfig) GetBackupKeepAmount() int32 {
	if x != nil {
		return x.BackupKeepAmount
	}
	return 0
}

type AgentServerConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayers            int32                  `protobuf:"varint,1,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	WorkerThreads         int32                  `protobuf:"varint,2,opt,name=workerThreads,proto3" json:"workerThreads,omitempty"`
	Branch                string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	UpdateSFOnStart       bool                   `protobuf:"varint,4,opt,name=updateSFOnStart,proto3" json:"updateSFOnStart,omitempty"`
	AutoRestart           bool                   `protobuf:"varint,5,opt,name=autoRestart,proto3" json:"autoRestart,omitempty"`
	AutoPause             bool                   `protobuf:"varint,6,opt,name=autoPause,proto3" json:"autoPause,omitempty"`
	AutoSaveOnDisconnect  bool                   `protobuf:"varint,7,opt,name=autoSaveOnDisconnect,proto3" json:"autoSaveOnDisconnect,omitempty"`
	AutoSaveInterval      int32                  `protobuf:"varint,8,opt,name=autoSaveInterval,proto3" json:"autoSaveInterval,omitempty"`
	DisableSeasonalEvents bool                   `protobuf:"varint,9,opt,name=disableSeasonalEvents,proto3" json:"disableSeasonalEvents,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AgentServerConfig) Reset() {
	*x = AgentServerConfig{}
	mi := &file_proto_ssmcloud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServerConfig) ProtoMessage() {}

func (x *AgentServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServerConfig.ProtoReflect.Descriptor instead.
func (*AgentServerConfig) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{1}
}

func (x *AgentServerConfig) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *AgentServerConfig) GetWorkerThreads() int32 {
	if x != nil {
		return x.WorkerThreads
	}
	return 0
}

func (x *AgentServerConfig) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *AgentServerConfig) GetUpdateSFOnStart() bool {
	if x != nil {
		return x.UpdateSFOnStart
	}
	return false
}

func (x *AgentServerConfig) GetAutoRestart() bool {
	if x != nil {
		return x.AutoRestart
	}
	return false
}

func (x *AgentServerConfig) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *AgentServerConfig) GetAutoSaveOnDisconnect() bool {
	if x != nil {
		return x.AutoSaveOnDisconnect
	}
	return false
}

func (x *AgentServerConfig) GetAutoSaveInterval() int32 {
	if x != nil {
		return x.AutoSaveInterval
	}
	return 0
}

func (x *AgentServerConfig) GetDisableSeasonalEvents() bool {
	if x != nil {
		return x.DisableSeasonalEvents
	}
	return false
}

type AgentConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AgentConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ServerConfig  *AgentServerConfig     `protobuf:"bytes,2,opt,name=serverConfig,proto3" json:"serverConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigResponse) Reset() {
	*x = AgentConfigResponse{}
	mi := &file_proto_ssmcloud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigResponse) ProtoMessage() {}

func (x *AgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigResponse.ProtoReflect.Descriptor instead.
func (*AgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfigResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AgentConfigResponse) GetServerConfig() *AgentServerConfig {
	if x != nil {
		return x.ServerConfig
	}
	return nil
}

type AgentConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigRequest) Reset() {
	*x = AgentConfigRequest{}
	mi := &file_proto_ssmcloud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigRequest) ProtoMessage() {}

func (x *AgentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigRequest.ProtoReflect.Descriptor instead.
func (*AgentConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{3}
}

func (x *AgentConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentConfigRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type AgentStateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Online             bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	Installed          bool                   `protobuf:"varint,2,opt,name=installed,proto3" json:"installed,omitempty"`
	Running            bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	Cpu                float32                `protobuf:"fixed32,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram                float32                `protobuf:"fixed32,5,opt,name=ram,proto3" json:"ram,omitempty"`
	InstalledSFVersion int64                  `protobuf:"varint,6,opt,name=installedSFVersion,proto3" json:"installedSFVersion,omitempty"`
	LatestSFVersion    int64                  `protobuf:"varint,7,opt,name=latestSFVersion,proto3" json:"latestSFVersion,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentStateRequest) Reset() {
	*x = AgentStateRequest{}
	mi := &file_proto_ssmcloud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStateRequest) ProtoMessage() {}

func (x *AgentStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStateRequest.ProtoReflect.Descriptor instead.
func (*AgentStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{4}
}

func (x *AgentStateRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *AgentStateRequest) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *AgentStateRequest) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *AgentStateRequest) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *AgentStateRequest) GetRam() float32 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *AgentStateRequest) GetInstalledSFVersion() int64 {
	if x != nil {
		return x.InstalledSFVersion
	}
	return 0
}

func (x *AgentStateRequest) GetLatestSFVersion() int64 {
	if x != nil {
		return x.LatestSFVersion
	}
	return 0
}

type AgentTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON string
	Completed     bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	Retries       int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTask) Reset() {
	*x = AgentTask{}
	mi := &file_proto_ssmcloud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTask) ProtoMessage() {}

func (x *AgentTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTask.ProtoReflect.Descriptor instead.
func (*AgentTask) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{5}
}

func (x *AgentTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentTask) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AgentTask) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AgentTask) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *AgentTask) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

type AgentTaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*AgentTask           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTaskList) Reset() {
	*x = AgentTaskList{}
	mi := &file_proto_ssmcloud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTaskList) ProtoMessage() {}

func (x *AgentTaskList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTaskList.ProtoReflect.Descriptor instead.
func (*AgentTaskList) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{6}
}

func (x *AgentTaskList) GetTasks() []*AgentTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_ssmcloud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{7}
}

var File_proto_ssmcloud_proto protoreflect.FileDescriptor

const file_proto_ssmcloud_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ssmcloud.proto\"a\n" +
	"\vAgentConfig\x12&\n" +
	"\x0ebackupInterval\x18\x01 \x01(\x05R\x0ebackupInterval\x12*\n" +
	"\x10backupKeepAmount\x18\x02 \x01(\x05R\x10backupKeepAmount\"\xf1\x02\n" +
	"\x11AgentServerConfig\x12\x1e\n" +
	"\n" +
	"maxPlayers\x18\x01 \x01(\x05R\n" +
	"maxPlayers\x12$\n" +
	"\rworkerThreads\x18\x02 \x01(\x05R\rworkerThreads\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12(\n" +
	"\x0fupdateSFOnStart\x18\x04 \x01(\bR\x0fupdateSFOnStart\x12 \n" +
	"\vautoRestart\x18\x05 \x01(\bR\vautoRestart\x12\x1c\n" +
	"\tautoPause\x18\x06 \x01(\bR\tautoPause\x122\n" +
	"\x14autoSaveOnDisconnect\x18\a \x01(\bR\x14autoSaveOnDisconnect\x12*\n" +
	"\x10autoSaveInterval\x18\b \x01(\x05R\x10autoSaveInterval\x124\n" +
	"\x15disableSeasonalEvents\x18\t \x01(\bR\x15disableSeasonalEvents\"s\n" +
	"\x13AgentConfigResponse\x12$\n" +
	"\x06config\x18\x01 \x01(\v2\f.AgentConfigR\x06config\x126\n" +
	"\fserverConfig\x18\x02 \x01(\v2\x12.AgentServerConfigR\fserverConfig\">\n" +
	"\x12AgentConfigRequest\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"\xe1\x01\n" +
	"\x11AgentStateRequest\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12\x1c\n" +
	"\tinstalled\x18\x02 \x01(\bR\tinstalled\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x02R\x03cpu\x12\x10\n" +
	"\x03ram\x18\x05 \x01(\x02R\x03ram\x12.\n" +
	"\x12installedSFVersion\x18\x06 \x01(\x03R\x12installedSFVersion\x12(\n" +
	"\x0flatestSFVersion\x18\a \x01(\x03R\x0flatestSFVersion\"\x7f\n" +
	"\tAgentTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\"1\n" +
	"\rAgentTaskList\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".AgentTaskR\x05tasks\"\a\n" +
	"\x05Empty2\xd4\x01\n" +
	"\fAgentService\x12.\n" +
	"\x0eGetAgentConfig\x12\x06.Empty\x1a\x14.AgentConfigResponse\x129\n" +
	"\x1aUpdateAgentConfigVersionIp\x12\x13.AgentConfigRequest\x1a\x06.Empty\x120\n" +
	"\x10UpdateAgentState\x12\x12.AgentStateRequest\x1a\x06.Empty(\x01\x12'\n" +
	"\rGetAgentTasks\x12\x06.Empty\x1a\x0e.AgentTaskListB?Z=github.com/SatisfactoryServerManager/ssmcloud-resources/protob\x06proto3"

var (
	file_proto_ssmcloud_proto_rawDescOnce sync.Once
	file_proto_ssmcloud_proto_rawDescData []byte
)

func file_proto_ssmcloud_proto_rawDescGZIP() []byte {
	file_proto_ssmcloud_proto_rawDescOnce.Do(func() {
		file_proto_ssmcloud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ssmcloud_proto_rawDesc), len(file_proto_ssmcloud_proto_rawDesc)))
	})
	return file_proto_ssmcloud_proto_rawDescData
}

var file_proto_ssmcloud_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ssmcloud_proto_goTypes = []any{
	(*AgentConfig)(nil),         // 0: AgentConfig
	(*AgentServerConfig)(nil),   // 1: AgentServerConfig
	(*AgentConfigResponse)(nil), // 2: AgentConfigResponse
	(*AgentConfigRequest)(nil),  // 3: AgentConfigRequest
	(*AgentStateRequest)(nil),   // 4: AgentStateRequest
	(*AgentTask)(nil),           // 5: AgentTask
	(*AgentTaskList)(nil),       // 6: AgentTaskList
	(*Empty)(nil),               // 7: Empty
}
var file_proto_ssmcloud_proto_depIdxs = []int32{
	0, // 0: AgentConfigResponse.config:type_name -> AgentConfig
	1, // 1: AgentConfigResponse.serverConfig:type_name -> AgentServerConfig
	5, // 2: AgentTaskList.tasks:type_name -> AgentTask
	7, // 3: AgentService.GetAgentConfig:input_type -> Empty
	3, // 4: AgentService.UpdateAgentConfigVersionIp:input_type -> AgentConfigRequest
	4, // 5: AgentService.UpdateAgentState:input_type -> AgentStateRequest
	7, // 6: AgentService.GetAgentTasks:input_type -> Empty
	2, // 7: AgentService.GetAgentConfig:output_type -> AgentConfigResponse
	7, // 8: AgentService.UpdateAgentConfigVersionIp:output_type -> Empty
	7, // 9: AgentService.UpdateAgentState:output_type -> Empty
	6, // 10: AgentService.GetAgentTasks:output_type -> AgentTaskList
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ssmcloud_proto_init() }
func file_proto_ssmcloud_proto_init() {
	if File_proto_ssmcloud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ssmcloud_proto_rawDesc), len(file_proto_ssmcloud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ssmcloud_proto_goTypes,
		DependencyIndexes: file_proto_ssmcloud_proto_depIdxs,
		MessageInfos:      file_proto_ssmcloud_proto_msgTypes,
	}.Build()
	File_proto_ssmcloud_proto = out.File
	file_proto_ssmcloud_proto_goTypes = nil
	file_proto_ssmcloud_proto_depIdxs = nil
}
