// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/ssmcloud.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BackupInterval   int32                  `protobuf:"varint,1,opt,name=backupInterval,proto3" json:"backupInterval,omitempty"`
	BackupKeepAmount int32                  `protobuf:"varint,2,opt,name=backupKeepAmount,proto3" json:"backupKeepAmount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_proto_ssmcloud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConfig) GetBackupInterval() int32 {
	if x != nil {
		return x.BackupInterval
	}
	return 0
}

func (x *AgentConfig) GetBackupKeepAmount() int32 {
	if x != nil {
		return x.BackupKeepAmount
	}
	return 0
}

type AgentServerConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayers            int32                  `protobuf:"varint,1,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	WorkerThreads         int32                  `protobuf:"varint,2,opt,name=workerThreads,proto3" json:"workerThreads,omitempty"`
	Branch                string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	UpdateSFOnStart       bool                   `protobuf:"varint,4,opt,name=updateSFOnStart,proto3" json:"updateSFOnStart,omitempty"`
	AutoRestart           bool                   `protobuf:"varint,5,opt,name=autoRestart,proto3" json:"autoRestart,omitempty"`
	AutoPause             bool                   `protobuf:"varint,6,opt,name=autoPause,proto3" json:"autoPause,omitempty"`
	AutoSaveOnDisconnect  bool                   `protobuf:"varint,7,opt,name=autoSaveOnDisconnect,proto3" json:"autoSaveOnDisconnect,omitempty"`
	AutoSaveInterval      bool                   `protobuf:"varint,8,opt,name=autoSaveInterval,proto3" json:"autoSaveInterval,omitempty"`
	DisableSeasonalEvents bool                   `protobuf:"varint,9,opt,name=disableSeasonalEvents,proto3" json:"disableSeasonalEvents,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AgentServerConfig) Reset() {
	*x = AgentServerConfig{}
	mi := &file_proto_ssmcloud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServerConfig) ProtoMessage() {}

func (x *AgentServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServerConfig.ProtoReflect.Descriptor instead.
func (*AgentServerConfig) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{1}
}

func (x *AgentServerConfig) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *AgentServerConfig) GetWorkerThreads() int32 {
	if x != nil {
		return x.WorkerThreads
	}
	return 0
}

func (x *AgentServerConfig) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *AgentServerConfig) GetUpdateSFOnStart() bool {
	if x != nil {
		return x.UpdateSFOnStart
	}
	return false
}

func (x *AgentServerConfig) GetAutoRestart() bool {
	if x != nil {
		return x.AutoRestart
	}
	return false
}

func (x *AgentServerConfig) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *AgentServerConfig) GetAutoSaveOnDisconnect() bool {
	if x != nil {
		return x.AutoSaveOnDisconnect
	}
	return false
}

func (x *AgentServerConfig) GetAutoSaveInterval() bool {
	if x != nil {
		return x.AutoSaveInterval
	}
	return false
}

func (x *AgentServerConfig) GetDisableSeasonalEvents() bool {
	if x != nil {
		return x.DisableSeasonalEvents
	}
	return false
}

type AgentGenericRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentGenericRequest) Reset() {
	*x = AgentGenericRequest{}
	mi := &file_proto_ssmcloud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentGenericRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGenericRequest) ProtoMessage() {}

func (x *AgentGenericRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGenericRequest.ProtoReflect.Descriptor instead.
func (*AgentGenericRequest) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{2}
}

func (x *AgentGenericRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type AgentConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AgentConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ServerConfig  *AgentServerConfig     `protobuf:"bytes,2,opt,name=serverConfig,proto3" json:"serverConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigResponse) Reset() {
	*x = AgentConfigResponse{}
	mi := &file_proto_ssmcloud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigResponse) ProtoMessage() {}

func (x *AgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ssmcloud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigResponse.ProtoReflect.Descriptor instead.
func (*AgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_ssmcloud_proto_rawDescGZIP(), []int{3}
}

func (x *AgentConfigResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AgentConfigResponse) GetServerConfig() *AgentServerConfig {
	if x != nil {
		return x.ServerConfig
	}
	return nil
}

var File_proto_ssmcloud_proto protoreflect.FileDescriptor

const file_proto_ssmcloud_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ssmcloud.proto\"a\n" +
	"\vAgentConfig\x12&\n" +
	"\x0ebackupInterval\x18\x01 \x01(\x05R\x0ebackupInterval\x12*\n" +
	"\x10backupKeepAmount\x18\x02 \x01(\x05R\x10backupKeepAmount\"\xf1\x02\n" +
	"\x11AgentServerConfig\x12\x1e\n" +
	"\n" +
	"maxPlayers\x18\x01 \x01(\x05R\n" +
	"maxPlayers\x12$\n" +
	"\rworkerThreads\x18\x02 \x01(\x05R\rworkerThreads\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12(\n" +
	"\x0fupdateSFOnStart\x18\x04 \x01(\bR\x0fupdateSFOnStart\x12 \n" +
	"\vautoRestart\x18\x05 \x01(\bR\vautoRestart\x12\x1c\n" +
	"\tautoPause\x18\x06 \x01(\bR\tautoPause\x122\n" +
	"\x14autoSaveOnDisconnect\x18\a \x01(\bR\x14autoSaveOnDisconnect\x12*\n" +
	"\x10autoSaveInterval\x18\b \x01(\bR\x10autoSaveInterval\x124\n" +
	"\x15disableSeasonalEvents\x18\t \x01(\bR\x15disableSeasonalEvents\"-\n" +
	"\x13AgentGenericRequest\x12\x16\n" +
	"\x06apiKey\x18\x01 \x01(\tR\x06apiKey\"s\n" +
	"\x13AgentConfigResponse\x12$\n" +
	"\x06config\x18\x01 \x01(\v2\f.AgentConfigR\x06config\x126\n" +
	"\fserverConfig\x18\x02 \x01(\v2\x12.AgentServerConfigR\fserverConfig2L\n" +
	"\fAgentService\x12<\n" +
	"\x0eGetAgentConfig\x12\x14.AgentGenericRequest\x1a\x14.AgentConfigResponseB?Z=github.com/SatisfactoryServerManager/ssmcloud-resources/protob\x06proto3"

var (
	file_proto_ssmcloud_proto_rawDescOnce sync.Once
	file_proto_ssmcloud_proto_rawDescData []byte
)

func file_proto_ssmcloud_proto_rawDescGZIP() []byte {
	file_proto_ssmcloud_proto_rawDescOnce.Do(func() {
		file_proto_ssmcloud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ssmcloud_proto_rawDesc), len(file_proto_ssmcloud_proto_rawDesc)))
	})
	return file_proto_ssmcloud_proto_rawDescData
}

var file_proto_ssmcloud_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ssmcloud_proto_goTypes = []any{
	(*AgentConfig)(nil),         // 0: AgentConfig
	(*AgentServerConfig)(nil),   // 1: AgentServerConfig
	(*AgentGenericRequest)(nil), // 2: AgentGenericRequest
	(*AgentConfigResponse)(nil), // 3: AgentConfigResponse
}
var file_proto_ssmcloud_proto_depIdxs = []int32{
	0, // 0: AgentConfigResponse.config:type_name -> AgentConfig
	1, // 1: AgentConfigResponse.serverConfig:type_name -> AgentServerConfig
	2, // 2: AgentService.GetAgentConfig:input_type -> AgentGenericRequest
	3, // 3: AgentService.GetAgentConfig:output_type -> AgentConfigResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ssmcloud_proto_init() }
func file_proto_ssmcloud_proto_init() {
	if File_proto_ssmcloud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ssmcloud_proto_rawDesc), len(file_proto_ssmcloud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ssmcloud_proto_goTypes,
		DependencyIndexes: file_proto_ssmcloud_proto_depIdxs,
		MessageInfos:      file_proto_ssmcloud_proto_msgTypes,
	}.Build()
	File_proto_ssmcloud_proto = out.File
	file_proto_ssmcloud_proto_goTypes = nil
	file_proto_ssmcloud_proto_depIdxs = nil
}
